[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[theme]
base = "dark"
backgroundColor = "#000510"
secondaryBackgroundColor = "#000818"
textColor = "#ffffff"

[browser]
gatherUsageStats = false

[runner]
fastReruns = true

[client]
showSidebarNavigation = false